[package]
name = "blockchain-demo"
version = "0.1.0"
authors = ["yunwei <1067852565@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sha2 = "0.9.1"
rust-crypto = "^0.2"
bincode = "1.3.1"
failure = "0.1.8"